# Array(数组)
* rank （一般表示数据维数）

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [9]:
a.size

3

In [6]:
a.shape

(3,)

In [7]:
a=a.reshape((1,-1))

In [8]:
a.shape

(1, 3)

上面的reshape中（（1，-1）） 第一个1代表一行，第二个-1其实是个占位符，没什么实际作用，在命令[8]中可以得证,下面也是一样的例证

In [9]:
a=np.array([1,2,3,4,5,6])

In [12]:
a=a.reshape(2,-1)

In [13]:
a.shape

(2, 3)

In [14]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a=np.zeros((3,3))

In [16]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

zeros用来创建0矩阵 或者说元素全为0的ndarray

In [17]:
a=np.ones((2,3))

In [18]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

所以ones函数用来创建元素全为1的ndarray
类似功能的还有full函数

In [19]:
a=np.full((3,3),0)

In [20]:
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

full函数用于创建元素全为第二个参数值的ndarray，第一个参数是一个tuple元组，用于表示要创建的维度，第二个参数是要填充的数值

eye函数，用于创建对角线元素全为1的对角矩阵（单位矩阵）

In [21]:
a=np.eye(3)

In [22]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

接受一个参数，表示矩阵的维数，对角阵肯定是方阵

random.random 用于创建元素全为0~1的随机值的ndarray

In [23]:
a=np.random.random((3,4))

In [24]:
a

array([[0.4290674 , 0.79266057, 0.91144309, 0.55452668],
       [0.10859984, 0.51837079, 0.22326007, 0.78782431],
       [0.32028295, 0.80139761, 0.7336456 , 0.70357627]])

# indexing and Boolean

In [1]:
a=np.range(1,12)

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
a=np.range(1,12)

AttributeError: module 'numpy' has no attribute 'range'

In [4]:
a=range(1,12)

In [5]:
a=a.reshape(3,4)

AttributeError: 'range' object has no attribute 'reshape'

In [6]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [7]:
a=a.reshape(3,-1)

In [8]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
a[-2:,1:3]

array([[ 6,  7],
       [10, 11]])

In [10]:
a[-2:][1:3]

array([[ 9, 10, 11, 12]])

所以在其他编程语言里这样貌似可行，但是python不接受这样的语法

In [11]:
b=a[-2:,1:3]

In [13]:
b.shape

(2, 2)

In [14]:
b=a[2,1:3]

In [15]:
b.shape

(2,)

In [16]:
b=a[1,2]

In [17]:
b

7

In [18]:
b.shape

()

从上面可以发现，如果在切片中使用整数，那么就会降维，同时，只有一个数字，没有维度，表示为（），如果只有一行元素，那么表示为（2,） 因为shape返回的元素是元组，但是实际上，这个2表示的是 一行有两个元素

In [19]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
a[np.arange(3),1]+=10

In [22]:
np.arange(3)

array([0, 1, 2])

arange产生整数序列，默认从0开始，到3，但不包括3，所以20句命令相当于
a[0:3,1]+=10,用来生成一个指定范围内的整数数组

In [24]:
np.arange(3,7)

array([3, 4, 5, 6])

In [26]:
a[[0,1,2],[1,1,1]]+=10

In [27]:
a

array([[ 1, 22,  3,  4],
       [ 5, 26,  7,  8],
       [ 9, 30, 11, 12]])

所以虽然不能写成a[2:][1:],但是 a[[],[]] 这样是可以的，arange其实和list很像，反正意思就是一个ndarray只接受一个list参数，至于里面是什么，不管
a[[0,1,2],[1,1,1]] 就是a[0,1]  a[1,1] a[2,1]

In [29]:
a[np.arange(3),[1,1,1]]+=10

In [30]:
a

array([[ 1, 32,  3,  4],
       [ 5, 36,  7,  8],
       [ 9, 40, 11, 12]])

所以ndarray切片有三种写法

In [33]:
result_index=a>10

In [34]:
result_index

array([[False,  True, False, False],
       [False,  True, False, False],
       [False,  True,  True,  True]])

In [35]:
a[result_index]

array([32, 36, 40, 11, 12])

这就是numpy中ndarray中布尔值的运用 true和false控制数值及其位置的显示或隐藏

或者可以直接

In [36]:
a[a>10]

array([32, 36, 40, 11, 12])

神奇的布尔值，神奇的numpy，神奇的ndarray

# 元素的数据类型

In [37]:
a=np.array([1,2])

In [38]:
a.dtype

dtype('int32')

dtype是用来判断array内部元素的数据类型  直接type(a)是a的类型

In [39]:
type(a)

numpy.ndarray

In [40]:
a=np.array([1.1,2.2])

In [41]:
a.dtype

dtype('float64')

In [42]:
a=np.array([1.1,2.2],dtype=np.int64)

In [43]:
a

array([1, 2], dtype=int64)

也就是说可以手动指定dtype，可以借此改变数字，就好像我的数据库里类型都是float，直接修改列定义的数据类型，就可以自动进行截断转换

In [44]:
b=np.array(a,dtype=np.int64)

In [45]:
b

array([1, 2], dtype=int64)

也可以基于已有数据进行修改，666

# 数学运算

In [51]:
a=np.array([[1,2],
          [3,4]])

In [10]:
b=np.array([[5,6],
          [7,8]])

In [53]:
a+b

array([[ 6,  8],
       [10, 12]])

In [54]:
np.add(a,b)

array([[ 6,  8],
       [10, 12]])

也就是说 直接相加和 np.add函数作用一样，同理，减法和np.subtract(a,b)
乘法  *  np.multiply(a,b)
除法  / np.divide(a,b)
这里的运算只是将位置对应位置的元素进行加减乘除
并不是矩阵乘法（点乘）

In [55]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

开方操作

In [56]:
b=np.array([[1,2,3],
            [4,5,6]])

In [57]:
a

array([[1, 2],
       [3, 4]])

In [58]:
a.dot(b)

array([[ 9, 12, 15],
       [19, 26, 33]])

这里dot就是点乘，相当于 a点乘b a右乘b  但是记住线性代数里的至少有一个维度相同  2×2 · 2×3=2×3

# 常用函数

### sum   axis参数

In [59]:
a

array([[1, 2],
       [3, 4]])

In [60]:
a.sum()

10

所以直接对ndarray求和，就是把里面所有的值进行相加,同时还可以有下面的写法，其实下面的才是更常见的写法

In [61]:
np.sum(a)

10

In [62]:
np.sum(a,axis=0)

array([4, 6])

axis=0 就是限定维度在列 求列和，（因为大部分时候一列是一个字段，所以求列和比较常用，所以axis=0表示求列和），既然开发了求列和，那就捎带，同理，axis=1 求行和

In [63]:
np.sum(a,axis=1)

array([3, 7])

In [32]:
c=np.array([[[1,2,3,4],[4,5,6,7]],
           [[7,8,9,10],[10,11,12,13]],
           [[13,14,15,16],[16,17,18,19]]
           ])

In [33]:
np.sum(c,axis=0)

array([[21, 24, 27, 30],
       [30, 33, 36, 39]])

In [34]:
np.sum(c,axis=1)

array([[ 5,  7,  9, 11],
       [17, 19, 21, 23],
       [29, 31, 33, 35]])

In [35]:
np.sum(c,axis=2)

array([[10, 22],
       [34, 46],
       [58, 70]])

### mean

In [64]:
np.mean(a,axis=0)

array([2., 3.])

In [65]:
np.mean(a,axis=1)

array([1.5, 3.5])

所以基本这些用于 基本统计量的 函数 其实都可以使用axis来指定
numpy用于科学计算   所以这个针对统计量的设计 很棒 

### uniform

In [67]:
np.random.uniform(3,4)

3.9309309594980335

 uniform用于生成一个指定范围内的随机数值

### tile

In [68]:
a

array([[1, 2],
       [3, 4]])

In [69]:
np.tile(a,(1,2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

把a作为一个元素，产生一个1行2列的array，也就是（a,a）

In [70]:
np.tile(a,(2,1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

把a作为一个元素，产生两行一列的array，也就是（a,
                               a）

In [71]:
np.tile(a,(3,3))

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4],
       [1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

同理，把a作为一个元素，产生一个3行3列的array

### argsort

In [72]:
a

array([[1, 2],
       [3, 4]])

In [73]:
np.argsort(a)

array([[0, 1],
       [0, 1]], dtype=int64)

In [74]:
b=np.array([[1,3,5,7],
            [12,3,5,2]])

In [75]:
b.argsort()

array([[0, 1, 2, 3],
       [3, 1, 2, 0]], dtype=int64)

b数组里每个list元素中有重复的元素
总体排序为 1,2,3,3,5,5,7,12
所以argsort是对b中每个list元素分别进行排序 默认是对每行（即每个list元素进行排序），也可以通过制定axis对列进行排序

In [76]:
b.argsort(axis=0)

array([[0, 0, 0, 1],
       [1, 1, 1, 0]], dtype=int64)

### 矩阵转置

In [78]:
b

array([[ 1,  3,  5,  7],
       [12,  3,  5,  2]])

In [79]:
b.T

array([[ 1, 12],
       [ 3,  3],
       [ 5,  5],
       [ 7,  2]])

In [81]:
np.transpose(b)

array([[ 1, 12],
       [ 3,  3],
       [ 5,  5],
       [ 7,  2]])

两种写法都可以实现转置

# 广播

In [84]:
a=np.array([[1,2,3],
           [4,5,7],
           [23,45,67],
           [12,25,35]
           ])

In [85]:
b=np.array([1,2,3])

想要实现a的每行（每个list元素）都与b相加，
* 可以通过循环实现（如果a数组非常大，那么for循环（迭代）会很影响性能）
* 使用tile实现这个功能
* 直接利用numpy的广播功能

In [89]:
for i in range(4):
    a[i,:]+=b

In [90]:
a

array([[ 2,  4,  6],
       [ 5,  7, 10],
       [24, 47, 70],
       [13, 27, 38]])

In [91]:
a+np.tile(b,(4,1))

array([[ 3,  6,  9],
       [ 6,  9, 13],
       [25, 49, 73],
       [14, 29, 41]])

In [92]:
a+b

array([[ 3,  6,  9],
       [ 6,  9, 13],
       [25, 49, 73],
       [14, 29, 41]])

numpy的广播功能可以将不同维度的数组进行相加，numpy会自动将低维度的数组转为相同维度，广播会在缺失维度和数值为1的维度上进行

In [11]:
b

array([[5, 6],
       [7, 8]])

In [12]:
b.size

4

### exp

In [26]:
np.exp(b)

array([[ 148.4131591 ,  403.42879349],
       [1096.63315843, 2980.95798704]])

In [25]:
np.e**b[0,0]

148.41315910257657

In [27]:
np.exp2(b)

array([[ 32.,  64.],
       [128., 256.]])

2为底数，b数组分别为指数，2\*\*5,2\*\*6
                  2\*\*7，2\*\*8
                 一般星号会被当成别的转义符，所以想要打出来，需要使用\进行转义

In [28]:
np.sin(b)

array([[-0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825]])

将输入的参数b作为x 返回y  y=sin（x） 类似这样的 所以返回值永远在1~-1之间

### concatenate

In [36]:
a = np.array([[1, 2], [3, 4]])

In [37]:
 b = np.array([[5, 6]])

In [38]:
 np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [40]:
b.T

array([[5],
       [6]])

In [42]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])

In [45]:
c=np.concatenate((a, b.T), axis=1)

In [46]:
c

array([[1, 2, 5],
       [3, 4, 6]])

In [56]:
np.split(c,[0,2],axis=1)

[array([], shape=(2, 0), dtype=int32), array([[1, 2],
        [3, 4]]), array([[5],
        [6]])]

In [57]:
np.split(c,2)

[array([[1, 2, 5]]), array([[3, 4, 6]])]

# numpy矩阵操作和线性方程组

In [58]:
from numpy.linalg import *

In [59]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [60]:
ary=([[1,2],
      [3,4]
     ])

In [61]:
inv(ary)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [62]:
eig(ary)

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

# 相关系数

In [63]:
np.corrcoef([1,0,1],[0,2,1])

array([[ 1.       , -0.8660254],
       [-0.8660254,  1.       ]])